#!/bin/sh
# SCRIPTS_DIR/sbin/lcd
# Control the lcd backlight, allows the changing of the backlight brightness 
# and turning the backlight on and off.

[ -h "${0}" ] &&
    script_path="$(/bin/readlink -f "${0}")" ||
    script_path="${0}"
. "${script_path%/*}/../lib/send_message.sh"
icon="xfpm-brightness-lcd"
icon_error="xfpm-brightness-lcd-invalid"
notify_opts="--category=device "

[ -n "${backlight}" ] || {
    for bl in "${sys_backlight_path:=/sys/class/backlight}"/*
    do
	[ -d "${bl}" ] && [ -f "${bl}/type" ] && {
	    read bl_type < "${bl}/type"
	    case "${bl_type}" in
		"platform")
		    backlight="${bl}"
		    break
		    ;;
		*)
		    backup="${bl}"
		    ;;
	    esac
	} || {
	    echo "Invalid backlight: ${bl}" >&2
	    exit 1
	}
    done
}

bl_brightness="${backlight:-${backup}}/brightness"
bl_max="${backlight:-${backup}}/max_brightness"
bl_power="${backlight:-${backup}}/bl_power"

[ -f ${bl_brightness} ] && [ -f ${bl_max} ] && [ -f ${bl_power} ] && {
    read current < "${bl_brightness}"
    read max < "${bl_max}"
    read power < "${bl_power}"
    case "${1}" in
	"up"|"+")
	    current=$(( ${current} + 1 ))
	    ;;
	"down"|"-")
	    current=$(( ${current} - 1 ))
	    ;;
	[0-9]*)
	    [ ${1} -gt ${max} ] &&
		current=${max} ||
		current=${1}
	    ;;
	"on")
	    power=0
	    ;;
	"off")
	    power=1
	    ;;
	"toggle")
	    power=$(( ! ${power} ))
	    ;;
	*)
	    echo "Usage: ${0} <action>"
	    echo
	    echo "ACTIONS"
	    echo "	up, +		Increase by 1"
	    echo "	down, -		Decrease by 1"
	    echo "	0-${max}	Set level"
	    echo "	on		Turn backlight on"
	    echo "	off		Turn backlight off"
	    echo "	toggle		Toggle backlight on/off"
	    echo
	    exit 1
	    ;;
    esac
    echo "${current}" > "${bl_brightness}"
    send_message "LCD Brightness:" "${current} / ${max}"
    echo "${power}" > "${bl_power}"
} || {
    send_message -e "LCD Brightness:" "Control Error"
}
