#!/bin/sh
# SCRIPTS_DIR/sbin/run_cron
# Run the scripts contained in the /etc/cron.PERIOD directories.

log="${LOG-/dev/null}"

## souce library scripts	{{{1
[ -h "${0}" ] &&
    script_p="$(readlink -f "${0}")" ||
    script_p="${0}"
lib_d="${script_p%/*/*}/lib"
. "${lib_d}/output.sh"

## Global Variables		{{{1
prefix="/etc"
dir_prefix="cron"

## Process Name and Arguments	{{{1

[ "${0##*.}" != "${0}" ] &&
    period="${0##*.}"	# name of the form run_cron.period

while [ ${#} -gt 0 ]
do
    if [ -z "${1##-*}" ]
    then

	# parse opt
	case "${1}" in
	    '-p'|'--prefix')
		prefix="${2%/}"
		shift
		;;
	    '-d'|'--dir-prefix')
		dir_prefix="${2}"
		shift
		;;
	    '-v'|'--verbose')
		verbose=true
		;;
	    *)
		warn "Invalid option '${1}'."
		;;
	esac

    else

	# it's the period definition
	[ -z "${period}" ] &&
	    period="${1}" ||
	    die "Multiple period definitions: '${period}' and '${1}'."

    fi
    shift
done


[ -n "${period}" ] ||
    die "No period specified."

dir="${prefix}/${dir_prefix}.${period}"
if [ -r "${dir}" -a -d "${dir}" ]
then

    for f in "${dir}"/*
    do
	if [ -r "${f}" -a -f "${f}" -a -x "${f}" -a "${f}" = "${f%~}" ]
	then

	    "${f}" >"${log}" 2>&1

	else

	    [ "${f}" = "${dir}/*" ] &&
		info "No scripts in directory: ${dir}." ||
		warn "Not a valid script: '${f}'."

	fi
    done

else

    die "Directory doesn't exist or is inaccessible: ${dir}"

fi
